spring:
  datasource:
    url: jdbc:postgresql://192.168.117.128:5432/stock_db
    username: hwet
    password: hwet
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    mvc:
      view:
        prefix: /templates/
        suffix: .html